### ISSUE TITLE
Technical Challenges

### ISSUE THREAD

**Issue by barnjamin** [dariocast/algorand-nft-loan#2]
Hello! Thanks for using Beaker to build this!

I'd like to solicit any feedback you might have from the development process. What did you find challenging? Where did it trip you up or fall short? Any docs you found especially lacking?

**Comment by dariocast** [comment]
Hi, I found particurarly challenging the use of api parameter such as assets or txns. The issue was that I. was not aware that, even if I was passing them as parameter to method call, I must pass them also from outside in specific arrays (address, accounts for txns ecc..). I think this is a limitation because forces the contracts to store global variable.

**Comment by barnjamin** [comment]
I see! This is a protocol/abi requirement and I agree that it can be quite awkward. 

In this specific case you should be able to specify the foreign types (asset/app/acct) in the arguments of the method and pass them directly as args rather than passing in the refs in an array later, maybe you've already done this.

And if it occured to you to use global state maybe you've seen the `DefaultArgument` setup in beaker, example here: https://github.com/algorand-devrel/beaker/blob/master/examples/amm/amm.py#L307-L309 that will allow you to completely omit the values from the call and have them resolved at call time.

Thanks again for the feedback! I welcome any more that you may have
